// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: blog.proto

package blogclient

import (
	"context"

	blogpb "blog/pb/blog"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CreatePostRequest     = blogpb.CreatePostRequest
	CreatePostResponse    = blogpb.CreatePostResponse
	DeletePostRequest     = blogpb.DeletePostRequest
	DeletePostResponse    = blogpb.DeletePostResponse
	GetAllPostsRequest    = blogpb.GetAllPostsRequest
	GetAllPostsResponse   = blogpb.GetAllPostsResponse
	GetPostDetailRequest  = blogpb.GetPostDetailRequest
	GetPostDetailResponse = blogpb.GetPostDetailResponse
	PostInfo              = blogpb.PostInfo
	UpdatePostRequest     = blogpb.UpdatePostRequest
	UpdatePostResponse    = blogpb.UpdatePostResponse

	Blog interface {
		CreatePost(ctx context.Context, in *CreatePostRequest, opts ...grpc.CallOption) (*CreatePostResponse, error)
		UpdatePost(ctx context.Context, in *UpdatePostRequest, opts ...grpc.CallOption) (*UpdatePostResponse, error)
		DeletePost(ctx context.Context, in *DeletePostRequest, opts ...grpc.CallOption) (*DeletePostResponse, error)
		GetAllPosts(ctx context.Context, in *GetAllPostsRequest, opts ...grpc.CallOption) (*GetAllPostsResponse, error)
		GetPostDetail(ctx context.Context, in *GetPostDetailRequest, opts ...grpc.CallOption) (*GetPostDetailResponse, error)
	}

	defaultBlog struct {
		cli zrpc.Client
	}
)

func NewBlog(cli zrpc.Client) Blog {
	return &defaultBlog{
		cli: cli,
	}
}

func (m *defaultBlog) CreatePost(ctx context.Context, in *CreatePostRequest, opts ...grpc.CallOption) (*CreatePostResponse, error) {
	client := blogpb.NewBlogClient(m.cli.Conn())
	return client.CreatePost(ctx, in, opts...)
}

func (m *defaultBlog) UpdatePost(ctx context.Context, in *UpdatePostRequest, opts ...grpc.CallOption) (*UpdatePostResponse, error) {
	client := blogpb.NewBlogClient(m.cli.Conn())
	return client.UpdatePost(ctx, in, opts...)
}

func (m *defaultBlog) DeletePost(ctx context.Context, in *DeletePostRequest, opts ...grpc.CallOption) (*DeletePostResponse, error) {
	client := blogpb.NewBlogClient(m.cli.Conn())
	return client.DeletePost(ctx, in, opts...)
}

func (m *defaultBlog) GetAllPosts(ctx context.Context, in *GetAllPostsRequest, opts ...grpc.CallOption) (*GetAllPostsResponse, error) {
	client := blogpb.NewBlogClient(m.cli.Conn())
	return client.GetAllPosts(ctx, in, opts...)
}

func (m *defaultBlog) GetPostDetail(ctx context.Context, in *GetPostDetailRequest, opts ...grpc.CallOption) (*GetPostDetailResponse, error) {
	client := blogpb.NewBlogClient(m.cli.Conn())
	return client.GetPostDetail(ctx, in, opts...)
}
