// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: comment.proto

package commentclient

import (
	"context"

	"comment/pb/comment"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CommentInfo                 = comment.CommentInfo
	CreateCommentRequest        = comment.CreateCommentRequest
	CreateCommentResponse       = comment.CreateCommentResponse
	GetCommentsByPostIDRequest  = comment.GetCommentsByPostIDRequest
	GetCommentsByPostIDResponse = comment.GetCommentsByPostIDResponse

	Comment interface {
		CreateComment(ctx context.Context, in *CreateCommentRequest, opts ...grpc.CallOption) (*CreateCommentResponse, error)
		GetCommentsByPostID(ctx context.Context, in *GetCommentsByPostIDRequest, opts ...grpc.CallOption) (*GetCommentsByPostIDResponse, error)
	}

	defaultComment struct {
		cli zrpc.Client
	}
)

func NewComment(cli zrpc.Client) Comment {
	return &defaultComment{
		cli: cli,
	}
}

func (m *defaultComment) CreateComment(ctx context.Context, in *CreateCommentRequest, opts ...grpc.CallOption) (*CreateCommentResponse, error) {
	client := comment.NewCommentClient(m.cli.Conn())
	return client.CreateComment(ctx, in, opts...)
}

func (m *defaultComment) GetCommentsByPostID(ctx context.Context, in *GetCommentsByPostIDRequest, opts ...grpc.CallOption) (*GetCommentsByPostIDResponse, error) {
	client := comment.NewCommentClient(m.cli.Conn())
	return client.GetCommentsByPostID(ctx, in, opts...)
}
