// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: blog.proto

package server

import (
	"context"

	"blog/internal/logic"
	"blog/internal/svc"
	blog "blog/pb/blog"
)

type BlogServer struct {
	svcCtx *svc.ServiceContext
	blog.UnimplementedBlogServer
}

func NewBlogServer(svcCtx *svc.ServiceContext) *BlogServer {
	return &BlogServer{
		svcCtx: svcCtx,
	}
}

func (s *BlogServer) CreatePost(ctx context.Context, in *blog.CreatePostRequest) (*blog.CreatePostResponse, error) {
	l := logic.NewCreatePostLogic(ctx, s.svcCtx)
	return l.CreatePost(in)
}

func (s *BlogServer) UpdatePost(ctx context.Context, in *blog.UpdatePostRequest) (*blog.UpdatePostResponse, error) {
	l := logic.NewUpdatePostLogic(ctx, s.svcCtx)
	return l.UpdatePost(in)
}

func (s *BlogServer) DeletePost(ctx context.Context, in *blog.DeletePostRequest) (*blog.DeletePostResponse, error) {
	l := logic.NewDeletePostLogic(ctx, s.svcCtx)
	return l.DeletePost(in)
}

func (s *BlogServer) GetAllPosts(ctx context.Context, in *blog.GetAllPostsRequest) (*blog.GetAllPostsResponse, error) {
	l := logic.NewGetAllPostsLogic(ctx, s.svcCtx)
	return l.GetAllPosts(in)
}

func (s *BlogServer) GetPostDetail(ctx context.Context, in *blog.GetPostDetailRequest) (*blog.GetPostDetailResponse, error) {
	l := logic.NewGetPostDetailLogic(ctx, s.svcCtx)
	return l.GetPostDetail(in)
}
