// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: comment.proto

package server

import (
	"context"

	"comment/internal/logic"
	"comment/internal/svc"
	"comment/pb/comment"
)

type CommentServer struct {
	svcCtx *svc.ServiceContext
	comment.UnimplementedCommentServer
}

func NewCommentServer(svcCtx *svc.ServiceContext) *CommentServer {
	return &CommentServer{
		svcCtx: svcCtx,
	}
}

func (s *CommentServer) CreateComment(ctx context.Context, in *comment.CreateCommentRequest) (*comment.CreateCommentResponse, error) {
	l := logic.NewCreateCommentLogic(ctx, s.svcCtx)
	return l.CreateComment(in)
}

func (s *CommentServer) GetCommentsByPostID(ctx context.Context, in *comment.GetCommentsByPostIDRequest) (*comment.GetCommentsByPostIDResponse, error) {
	l := logic.NewGetCommentsByPostIDLogic(ctx, s.svcCtx)
	return l.GetCommentsByPostID(in)
}
